---
title: Election Forecast 1
author: Alex Heuss
date: '2024-09-05'
slug: testing-blog-upload
categories: [election-prediction]
tags: [president]
---
```{r, setup, echo = FALSE, message = FALSE}
library(ggplot2)
library(tidyverse)

#note: code to build site - build_site(build_rmd=TRUE)
```

This is my first blog post, for the week of September 2nd. The primary method of prediction for this week is a model based on the results of the past two presidential elections, 2016 and 2020. 

```{r, loading data, echo= FALSE, message = FALSE} 
# The code for this post is heavily based on the code that was introduced in section this week. 

nat_data <- read_csv("popvote_1948-2020.csv")
state_data <- read_csv("clean_wide_state_2pv_1948_2020.csv")

```
```{r, initial data wrangling, echo = FALSE}
nat_wide <- 
  nat_data |> 
  select(year, party, pv2p) |>
  pivot_wider(names_from = party, values_from = pv2p) |>
  mutate(winner = ifelse(republican > democrat, "republican", "democrat"))
  
```

```{r, echo = FALSE}
nat_summary <- 
  nat_wide |> 
  mutate(winner = ifelse(winner == "democrat", "Democrat", "Republican")) |>
  group_by(winner) |>
  summarize(races_won = n())

nat_summary |>
  knitr::kable(col.names = c("Party", "Races Won"), caption = "Presidential races won by each party since 1948")
```
One thing I take away from this chart is how little data we actually have to train prediction models on. There have only been 19 presidential elections since 1948.

```{r, bar chart, echo= FALSE}

my_theme <- theme_bw() + theme(legend.position = "none")

options(repr.plot.width=20, repr.plot.height=8)

nat_data |>
  ggplot(aes(x = year, y = pv2p, color = party)) +
  geom_line() +
  scale_color_manual(values = c("#00AEF3", "#E81B23")) + 
  labs(x = "", y = "% Two Party Vote Share", title = "Presidential Two Party Vote Share") + 
  my_theme

```







